import type { Category } from './types';

export const STORAGE_KEY = 'shoppingListApp';
export const SCHEMA_VERSION = 1;

export const DEFAULT_CATEGORY_ORDER = [
  'fruits',
  'legumes',
  'viandes',
  'poissons',
  'laitiers',
  'boulangerie',
  'epicerie',
  'surgeles',
  'boissons',
  'hygiene',
  'entretien',
  'bricolage',
  'pharmacie',
  'vetements',
  'animaux',
  'jeux',
  'scolaire',
  'electromenager',
  'auto',
  'fetes',
  'sport',
  'voyage',
  'autre',
];

export const DEFAULT_CATEGORIES: Record<string, Category> = {
  fruits: {
    id: 'default_fruits',
    icon: '🍎',
    color: 'var(--cat-fruits)',
    priority: 2,
    keywords: ['pomme','banane','orange','poire','fraise','raisin','kiwi','mangue','ananas','melon','pastèque','citron','pamplemousse','abricot','pêche','prune','cerise','framboise','myrtille','clémentine','mandarine','fruit','nectarine','grenade','figue','litchi','papaye','fruit de la passion','noix de coco','avocat','cassis','groseille','mûre'],
  },
  legumes: {
    id: 'default_legumes',
    icon: '🥬',
    color: 'var(--cat-legumes)',
    priority: 2,
    keywords: ['tomate','salade','carotte','courgette','poivron','oignon','ail','pomme de terre','haricot','petit pois','brocoli','chou','aubergine','concombre','radis','navet','poireau','épinard','champignon','légume','échalote','céleri','laitue','mâche','endive','artichaut','asperge','betterave','chou-fleur','fenouil','patate','citrouille','courge','potiron','maïs','persil','basilic','coriandre','ciboulette'],
  },
  viandes: {
    id: 'default_viandes',
    icon: '🥩',
    color: 'var(--cat-viandes)',
    priority: 2,
    keywords: ['poulet','boeuf','porc','agneau','veau','dinde','canard','steak','côtelette','rôti','escalope','saucisse','jambon','bacon','merguez','viande','hachée','haché','bifteck','entrecôte','filet','gigot','lapin','pintade','caille','boudin','paupiette','émincé','brochette','chipolata','andouillette','blanc de poulet','cuisse de poulet','magret'],
  },
  poissons: {
    id: 'default_poissons',
    icon: '🐟',
    color: 'var(--cat-poissons)',
    priority: 2,
    keywords: ['saumon','thon','cabillaud','dorade','truite','sardine','crevette','moule','huître','crabe','homard','calamar','poisson','lieu','colin','merlan','sole','bar','loup','maquereau','anchois','hareng','raie','fruits de mer','coquille saint-jacques','bulot','bigorneaux','langoustine','poulpe','seiche','surimi'],
  },
  laitiers: {
    id: 'default_laitiers',
    icon: '🥛',
    color: 'var(--cat-laitiers)',
    priority: 2,
    keywords: ['lait','yaourt','fromage','beurre','crème','œuf','emmental','gruyère','camembert','chèvre','mozzarella','parmesan','roquefort','fromage blanc','crème fraîche','mascarpone','ricotta','feta','brie','comté','cantal','reblochon','raclette','gouda','mimolette','petit-suisse','faisselle','babybel','kiri','boursin','philadelphia','crème anglaise'],
  },
  epicerie: {
    id: 'default_epicerie',
    icon: '🛍️',
    color: 'var(--cat-epicerie)',
    priority: 2,
    keywords: ['riz','pâtes','farine','sucre','sel','poivre','huile','vinaigre','conserve','sauce','céréales','café','thé','chocolat','confiture','miel','biscuit','spaghetti','macaroni','coquillette','tagliatelle','nouille','semoule','quinoa','boulgour','lentille','pois chiche','haricot sec','levure','chapelure','maïzena','purée','ketchup','mayonnaise','moutarde','cornichon','olive','câpre','épice','herbe','bouillon cube','soupe','barre de céréale','compote','nutella'],
  },
  surgeles: {
    id: 'default_surgeles',
    icon: '❄️',
    color: 'var(--cat-surgeles)',
    priority: 2,
    keywords: ['surgelé','glace','pizza','frite','poisson pané','légume surgelé','sorbet','crème glacée','esquimau','cornet','glaçon','fruit surgelé','nugget','plat préparé','lasagne','gratin','quiche','tarte flambée','croûte pizza'],
  },
  boissons: {
    id: 'default_boissons',
    icon: '🥤',
    color: 'var(--cat-boissons)',
    priority: 1,
    keywords: ['eau','jus','soda','vin','bière','coca','limonade','sirop','boisson','pepsi','fanta','sprite','orangina','perrier','vittel','evian','badoit','thé glacé','ice tea','nectar','smoothie','champagne','rosé','rouge','blanc','cidre','pastis','whisky','rhum','vodka','gin','apéritif','digestif','liqueur'],
  },
  boulangerie: {
    id: 'default_boulangerie',
    icon: '🥖',
    color: 'var(--cat-boulangerie)',
    priority: 2,
    keywords: ['pain','baguette','croissant','brioche','gâteau','tarte','viennoiserie','pain de mie','pain complet','pain de campagne','ficelle','pain au chocolat','chocolatine','chausson aux pommes','éclair','religieuse','mille-feuille','chouquette','macaron','financier','madeleine','cookie','brownie','muffin','donut','cupcake'],
  },
  hygiene: {
    id: 'default_hygiene',
    icon: '🧴',
    color: 'var(--cat-hygiene)',
    priority: 2,
    keywords: ['savon','shampoing','dentifrice','brosse à dents','déodorant','gel douche','papier toilette','mouchoir','coton','coton-tige','après-shampoing','masque capillaire','laque','gel coiffant','mousse','parfum','eau de toilette','rasoir','mousse à raser','lame','crème à raser','serviette hygiénique','tampon','protège-slip','lingette','démaquillant','eau micellaire','crème visage','crème mains','bain de bouche','fil dentaire'],
  },
  entretien: {
    id: 'default_entretien',
    icon: '🧽',
    color: 'var(--cat-entretien)',
    priority: 2,
    keywords: ['lessive','liquide vaisselle','éponge','nettoyant','javel','produit ménage','serpillière','balai','adoucissant','détachant','tablette','capsule','produit vaisselle','lave-vitre','nettoyant sol','désinfectant','spray','multi-usage','sac poubelle','lavette','chiffon','essuie-tout','papier absorbant','scotch-brite','brosse','pelle','anti-calcaire','déboucheur','wc','canard wc'],
  },
  bricolage: {
    id: 'default_bricolage',
    icon: '🔨',
    color: 'var(--cat-bricolage)',
    priority: 2,
    keywords: ['marteau','tournevis','vis','clou','scie','perceuse','pince','clé','tenaille','niveau','mètre','lime','rabot','serre-joint','clé à molette','pinceau','rouleau','peinture','vernis','planche','bois','ciment','ruban adhésif','câble','fil électrique','ampoule','douille','interrupteur','chevilles','écrou','boulon','rondelle'],
  },
  pharmacie: {
    id: 'default_pharmacie',
    icon: '💊',
    color: 'var(--cat-pharmacie)',
    priority: 2,
    keywords: ['doliprane','aspirine','paracétamol','ibuprofène','pansement','compresse','alcool','thermomètre','seringue','bétadine','antibiotique','cachets','gélule','médicament','crème hydratante','arnica','biafine','antiseptique','bandage','sparadrap','vitamine','complément alimentaire','homéopathie','granules','spray nasal','collyre','pastille'],
  },
  vetements: {
    id: 'default_vetements',
    icon: '👕',
    color: 'var(--cat-vetements)',
    priority: 2,
    keywords: ['jupe','pantalon','chemise','chaussure','pull','veste','robe','short','t-shirt','tee-shirt','jean','manteau','blouson','gilet','cardigan','sweat','polo','chemisier','costume','cravate','écharpe','bonnet','chapeau','casquette','gant','chaussette','collant','sous-vêtement','soutien-gorge','culotte','slip','caleçon','pyjama','basket','botte','sandale','espadrille','ceinture'],
  },
  animaux: {
    id: 'default_animaux',
    icon: '🐾',
    color: 'var(--cat-animaux)',
    priority: 2,
    keywords: ['croquette','pâtée','friandise','litière','couchage','gamelle','jouet pour chat','jouet pour chien','laisse','collier','harnais','cage','aquarium','nourriture poisson','nourriture chat','nourriture chien','nourriture oiseau','foin','shampoing animal','antiparasitaire','vermifuge','brosse animal','peigne animal','arbre à chat','griffoir','os à mâcher','balle pour chien','canne à pêche chat'],
  },
  jeux: {
    id: 'default_jeux',
    icon: '🎮',
    color: 'var(--cat-jeux)',
    priority: 2,
    keywords: ['lego','poupée','puzzle','livre','jeu de société','carte','jeu de carte','figurine','peluche','construction','playmobil','coloriage','crayon de couleur','peinture enfant','pâte à modeler','slime','bille','toupie','yo-yo','console','jeu vidéo','manette','barbie','voiture miniature','train jouet','kapla','duplo','livre enfant','album jeunesse','bd','manga','roman','conte'],
  },
  scolaire: {
    id: 'default_scolaire',
    icon: '📚',
    color: 'var(--cat-scolaire)',
    priority: 2,
    keywords: ['cahier','stylo','crayon','gomme','trousse','sac à dos','cartable','classeur','feuille','copie double','agenda','règle','équerre','compas','rapporteur','taille-crayon','correcteur','blanco','surligneur','stabilo','feutre','marqueur','colle','ciseaux','scotch','agrafeuse','agrafe','perforatrice','pochette plastique','protège-cahier','intercalaire','calculatrice','dictionnaire','cahier de texte','ardoise','porte-vue','chemise carton','trombones','post-it','cahier de brouillon'],
  },
  electromenager: {
    id: 'default_electromenager',
    icon: '💻',
    color: 'var(--cat-electromenager)',
    priority: 2,
    keywords: ['souris','clavier','clé usb','câble hdmi','chargeur','coque','écouteur','câble usb-c','aspirateur','grille-pain','bouilloire','micro-onde','batterie','pile','chargeur téléphone','adaptateur','multiprise','rallonge','casque audio','enceinte','bluetooth','webcam','micro','souris sans fil','tapis de souris','disque dur','ssd','carte sd','filtre café','sac aspirateur','cafetière','mixeur','blender','robot cuisine','fer à repasser','planche à repasser','sèche-cheveux','lisseur','rasoir électrique','brosse à dent électrique','balance','ventilateur','radiateur','lampe','ampoule led'],
  },
  auto: {
    id: 'default_auto',
    icon: '🚗',
    color: 'var(--cat-auto)',
    priority: 2,
    keywords: ['huile moteur','lave-glace','balai essuie-glace','essuie-glace','ampoule h7','ampoule auto','tapis voiture','gilet jaune','triangle','support téléphone','chargeur voiture','liquide refroidissement','antigel','dégivrant','grattoir','brosse neige','éponge voiture','shampooing auto','polish','cire','lustrant','nettoyant jante','parfum voiture','désodorisant','filtre habitacle','filtre air','balai coffre','câble démarrage','compresseur','gonfleur','cric','manomètre','bidon','jerrican','kit réparation','antivol','cadenas'],
  },
  fetes: {
    id: 'default_fetes',
    icon: '🎁',
    color: 'var(--cat-fetes)',
    priority: 2,
    keywords: ['bougie anniversaire','ruban','papier cadeau','carte anniversaire','carte vœux','enveloppe','ballon gonflable','guirlande','décoration','serpentin','confetti','nappe jetable','assiette jetable','gobelet jetable','paille','bougie','bougie parfumée','bougeoir','photophore','nœud','bolduc','sachet cadeau','boîte cadeau','étiquette cadeau','déguisement','masque','perruque','maquillage','paillettes','cotillon','pinata','ballon hélium','cadre photo','album photo'],
  },
  sport: {
    id: 'default_sport',
    icon: '⚽',
    color: 'var(--cat-sport)',
    priority: 2,
    keywords: ['ballon','corde à sauter','gourde','sac de sport','raquette','balle','tapis yoga','tapis sport','élastique','haltère','poids','vélo','casque vélo','antivol vélo','pompe vélo','chambre à air','rustine','bidon vélo','protège-tibias','genouillère','coudière','sangle','short sport','legging','brassière','chaussure sport','basket sport','running','chaussette sport','t-shirt sport','maillot','serviette sport','tente','sac de couchage','matelas gonflable','lampe frontale','briquet','allumette','gourde randonnée','bâton randonnée','sac à dos randonnée','carte ign','boussole','jumelle','camping'],
  },
  voyage: {
    id: 'default_voyage',
    icon: '✈️',
    color: 'var(--cat-voyage)',
    priority: 2,
    keywords: ['valise','adaptateur prise','cadenas valise','étiquette bagage','oreiller voyage','coussin voyage','masque nuit','bouchon oreille','trousse toilette','fiole voyage','flacon voyage','mini format','passeport','porte-passeport','porte-carte','ceinture voyage','pochette voyage','sac voyage','housse valise','balance bagage','cadenas tsa','convertisseur','guide voyage','carte routière','atlas','anti-moustique','crème solaire','lunette soleil','chapeau soleil','paréo','maillot de bain','tong','sandale plage','serviette plage','sac plage','bouée','brassard','tuba','masque plongée','palme'],
  },
  autre: {
    id: 'default_autre',
    icon: '📦',
    color: 'var(--cat-autre)',
    priority: 0,
    keywords: [],
  },
};
